#!/bin/bash

/usr/bin/docker run -d --name ubio-mysql \
    --env-file /opt/ubio/config/production.env \
    -p 3306:3306 \
    -v /opt/ubio/mysql:/var/lib/mysql \
    -v /opt/ubio/backup:/opt/ubio/backup \
    -v /opt/ubio/config/my.cnf:/etc/mysql/my.cnf \
  mblab/ubio-mysql
